apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-2-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-2
  template:
    metadata:
      labels:
        app: project-2
    spec:
      containers:
      - name: project-2
        image: deekshithamala/project-2
        ports:
        - containerPort: 80
